#!/bin/sh

if [ "$1" = "configure" ] ; then

  mv /lib/systemd/system/centreon_vmware-systemd /lib/systemd/system/centreon_vmware.service
  mv /etc/centreon/centreon_vmware-conf.pm /etc/centreon/centreon_vmware.pm

  systemctl daemon-reload
  systemctl enable centreon_vmware.service
  systemctl restart centreon_vmware.service

fi
exit 0
